/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "contract-messaging-document-data"

pluginManagement {
    plugins {
        id("com.projectronin.interop.gradle.junit") version "2.2.1"
        id("com.projectronin.interop.gradle.publish") version "2.2.1"
        id("com.projectronin.interop.gradle.version") version "2.2.1"
        id("com.projectronin.event.contract") version "1.0.0"
    }

    repositories {
        maven {
            url = uri("https://repo.devops.projectronin.io/repository/maven-public/")
        }
        mavenLocal()
        gradlePluginPortal()
    }
}
